spring:
  application:
    name: spring-cloud-gateway
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 1MB
      location: /
  cloud:
    gateway:
      routes:
        - id: bulletscreen
          # 重点！/info必须使用http进行转发，lb代表从注册中心获取服务
          uri: lb://bullet
          predicates:
          # 重点！转发该路径！
          - Path=/bullet/info/**
        - id: bulletscreen
          # 重点！lb:ws://代表从注册中心获取服务，并且转发协议为websocket，这种格式怀疑人生！
          uri: lb:ws://bullet
          predicates:
          # 转发/bullet端点下的所有路径
          - Path=/bullet/**
server:
  port: 8899
eureka:
  client:
    service-url:
      defaultZone: http://eureka.ljryh.com/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug
